// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpjtsqajpmquhpfxjkbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwanRzcWFqcG1xdWhwZnhqa2JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTg2ODQsImV4cCI6MjA3NDY3NDY4NH0.64gNFlsj-Vo0ZPEuu9hnqWTOjl9UtDp-bnpwLs6hp8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});